# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  Exclude:
    - 'db/migrate/**/*'
    - 'db/schema*.rb'
    - 'db/queue_schema.rb'
    - 'saas/db/untenanted_migrate/**/*'
    - 'saas/db/untenanted_schema.rb'
