<%
  config_path = if Sabha.saas?
    File.join(Rails.root, "saas", "config", "database.yml")
  else
    File.join("config", "database.sqlite.yml")
  end
%>
<%= ERB.new(File.read(config_path)).result %>
